### ISSUE TITLE
Mettre en place un système de Routing. Tu dois, grâce à une URL, être capable de rediriger la requête, vers un contrôlleur défini, ainsi qu'une méthode de ce même contrôlleur.

### ISSUE THREAD

**Issue by kevinniel** [WainlaiN/Projet-5#1]
Mettre en place un système de Routing. Tu dois, grâce à une URL, être capable de rediriger la requête, vers un contrôlleur défini, ainsi qu'une méthode de ce même contrôlleur.

**Comment by WainlaiN** [comment]
done

**Comment by WainlaiN** [comment]
using altorouter
