### ISSUE TITLE
Architecture

### ISSUE THREAD

**Issue by kevinniel** [WainlaiN/Projet-5#4]
Il faut bien penser à séparer la partie faisant fonctionner ton MVC, de la partie "modifiable" qui se SERT du MVC. Crée donc un dossier par exemple "core", dans lequel tu mettras tout le code qui permettra à ton architecture MVC de fonctionner. Par exemple, tous les fichiers qui vont gérer le Routing doivent être dans ce dossier "core". A contrario, le ou les fichiers contenant les routes doivent être dans la partie "modifiable" de ton application.

**Comment by WainlaiN** [comment]
done
